# Generated by Django 2.0.5 on 2018-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='/media/profile_banner/default.png', upload_to='profile_banner/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
