# Generated by Django 2.0.5 on 2018-06-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
