# Generated by Django 2.0.5 on 2018-06-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='designs/')),
                ('description', models.TextField(default='', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DesignComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=500)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Design')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatusComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Status')),
            ],
        ),
    ]
