# Generated by Django 2.0.5 on 2018-06-10 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180608_1408'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
            ],
        ),
        migrations.RenameField(
            model_name='design',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='designcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuscomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuslike',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Status'),
        ),
        migrations.AddField(
            model_name='designlike',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Design'),
        ),
        migrations.AddField(
            model_name='designlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile'),
        ),
    ]
