# Generated by Django 2.0.5 on 2018-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20180602_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
